name: blogAPI CI/CD
on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on:ubuntu-latest
  step:
    -name:push repo
     uses:actions/checkout@v3
    -name:print hello
    run:echo"Hello World"
